### ISSUE TITLE
Closure Compiler

### ISSUE THREAD

**Issue by banksJeremy** [jbitor/issues#5]
Is there a convenient way to use Google closure compiler with Go? It might be nice to try.

**Comment by banksJeremy** [comment]
[soheilhy/glosure](https://github.com/soheilhy/glosure) is a 13-day old library in this direction.

**Comment by banksJeremy** [comment]
This seems to work alright, see jbitor/webclient@f409a17 (and jbitor/jbitor@476ac27), but Java 7 is a really tough dependency to accept. This library doesn't have a nice built-in way to detect that it's missing and fall-back, so I'd have some work to do if I wanted to make it an enhancement, rather than a requirement.

It's not worth it, particularly given that we're not doing anything too complicated with JavaScript.

**Comment by soheilhy** [comment]
@jeremybanks Glosure had support for the closure REST API, but I didn't expose it in the initial version. I just pushed a version that can use the closure REST API instead of the jar file. You can set `cc.UseClosureApi = true` to make sure the code does not use Java.

**Comment by banksJeremy** [comment]
@soheilhy Wow, thanks for the quick enhancement. I'll check it out. :)
